# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true


# The Minecraft version must agree with the Forge version to get a valid artifact
minecraft_version=26.1.1
# The Minecraft version range can use any release version of Minecraft as bounds.
# Snapshots, pre-releases, and release candidates are not guaranteed to sort properly
# as they do not follow standard versioning conventions.
minecraft_version_range=[26.1]
# The Forge version must agree with the Minecraft version to get a valid artifact
neo_version=26.1.1.0-beta

## Mod Properties

# The unique mod identifier for the mod. Must be lowercase in English locale. Must fit the regex [a-z][a-z0-9_]{1,63}
# Must match the String constant located in the main mod class annotated with @Mod.
mod_id=ruins
# The human-readable display name for the mod.
mod_name=Ruins (Structure Spawning System)
# The license of the mod. Review your options at https://choosealicense.com/. All Rights Reserved is the default.
mod_license=https://atomicstryker.github.io/
# The mod version. See https://semver.org/
mod_version=26.1.1.1NF
curseforge_changelog='updated to MC 26.1.1 and neoforge 26.1.1.0-beta'
# The group ID for the mod. It is only important when publishing as an artifact to a Maven repository.
# This should match the base package used for the mod sources.
# See https://maven.apache.org/guides/mini/guide-naming-conventions.html
mod_group_id=atomicstryker.ruins
# The authors of the mod. This is a simple text string that is used for display purposes in the mod list.
mod_authors=AtomicStryker
# The description of the mod. This is a simple multiline text string that is used for display purposes in the mod list.
mod_description=Structures from template files spawn in the world randomly

curseforge_id=227873
