org.gradle.caching=true
org.gradle.parallel=true

net.minecraftforge.gradle.merge-source-sets=true

minecraft_version=26.1.2
forge_version=64.0.0


loader_version_range=[64,)

## Mod Properties

# The unique mod identifier for the mod. Must be lowercase in English locale. Must fit the regex [a-z][a-z0-9_]{1,63}
# Must match the String constant located in the main mod class annotated with @Mod.
mod_id=ruins
# The human-readable display name for the mod.
mod_name=Ruins (Structure Spawning System)
# The license of the mod. Review your options at https://choosealicense.com/. All Rights Reserved is the default.
mod_license=https://atomicstryker.github.io/
# The mod version. See https://semver.org/
mod_version=26.1.2.1
curseforge_changelog='ported to MC 26.1.2 and Forge 64.0.0'
# The group ID for the mod. It is only important when publishing as an artifact to a Maven repository.
# This should match the base package used for the mod sources.
# See https://maven.apache.org/guides/mini/guide-naming-conventions.html
mod_group_id=atomicstryker.ruins
# The authors of the mod. This is a simple text string that is used for display purposes in the mod list.
mod_authors=AtomicStryker
# The description of the mod. This is a simple multiline text string that is used for display purposes in the mod list.
mod_description=Structures from template files spawn in the world randomly

# ruins mod curseforge id
curseforge_id=227873
