# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[37,)" #mandatory forge version
license="AtomicStrykers License http://atomicstryker.net/about.php"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/issues" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="infernalmobs" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="${file.jarVersion}" #mandatory
 # A display name for the mod
displayName="Infernal Mobs" #mandatory
# A URL to query for updates for this mod. See the JSON update specification <here>
updateJSONURL="http://www.atomicstryker.net/updatemanager/infernalmobs.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="http://atomicstryker.org/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="logo.png" #optional
# A text field displayed in the mod UI
# credits="" #optional
# A text field displayed in the mod UI
authors="AtomicStryker" #optional
# The description text for the mod (multi line!) (#mandatory)
description="Diablo Style random Enchantments on Entities! Harder fights! More XP and enchanted loot!"
